from telegram.sections.IdleHandler import IdleHandler
from telegram.sections.CardCreationHandler import CardCreationHandler
from telegram.sections.SettingsHandler import SettingsHandler
from telegram.sections.RecomendationHandler import RecomendationHandler
from telegram.sections.CardMenuHandler import CardMenuHandler
from telegram.sections.AdminHandler import AdminHandler
from telegram.sections.PaymentHandler import PaymentHandler
