from telegram.sections.IdleHandler import IdleHandler
from telegram.sections.CardCreationHandler import CardCreationHandler
from telegram.sections.SettingsHandler import SettingsHandler
from telegram.sections.RecomendationHandler import RecomendationHandler
